### ISSUE TITLE
[feature request] make `elp eqwalize` return nonzero on found type errors

### ISSUE THREAD

**Issue by zerth** [WhatsApp/erlang-language-platform#20]
### Describe the bug

If invoking `eqwalizer` results in type errors, it would be nice if `elp` returned nonzero.  A few cases come to mind where that could be beneficial:
1. eqwalizing in a loop or otherwise against multiple modules and breaking on the first failure
2. eqwalizing while editing/rebasing a long history of commits (e.g., `elp eqwalize X && git rebase --continue`)
3. eqwalizing as a condition of a `git bisect` run

I know that finding type errors is not a failure of the tool, but think this would make sense from a user perspective.

### To Reproduce

```
-module(some_mod_with_errors).
-spec x(y) -> z; (term()) -> undefined.
x(_) -> z.
```
```
elp eqwalize some_mod_with_errors
```

### Expected behavior

```
% elp eqwalize some_mod_with_errors && echo ok || echo failed
...
failed
```

### Actual behavior

```
% elp eqwalize some_mod_with_errors && echo ok || echo failed
...
error: incompatible_types
  ┌─ some_mod_with_errors.erl:3:9
  │
4 │ x(_) -> z.
  │         ^ 'z'.
Expression has type:   'z'
Context expected type: 'undefined'

1 ERROR
ok
```

**Comment by robertoaloi** [comment]
It makes sense to me. If we want to ensure backward compatibility, we could implement this behaviour via an optional `-f` (`--fail`) flag. @alanz @VLanvin opinions?

**Comment by VLanvin** [comment]
Makes sense to me, but as you said @robertoaloi it should definitely be a flag. There are contexts where we don't want this behaviour.

**Comment by tsloughter** [comment]
Came to ask for the same thing but for usage in CI. In projects using `elp` for type checking before PR merges they are getting the false impression by doing this https://github.com/open-telemetry/opentelemetry-erlang/blob/main/.github/workflows/erlang.yml#L148-L149 that there aren't any eqWAlizer errors in the code being merged :)

**Comment by tsloughter** [comment]
Also, while I'm happy with whatever doesn't require me to write a pipe -> grep of the stdout to check for "# ERROR" I am curious why this shouldn't be the default? What scenario would you want it to always return 0 @VLanvin ? In the case of not wanting a script to fail if `elp` command fails you can just `| true` right? Are there non-script cases you are thinking of that this is needed to be the default?

I also think if its the default to always return `0` then the issue of people putting it in CI and not realizing it is passing because it will never fail will take a while to realize, even if its documented.
