### ISSUE TITLE
rebar3 Integration Docs are Very Outdated

### ISSUE THREAD

**Issue by i-am-linja** [WhatsApp/erlang-language-platform#52]
### Problem

The rebar3 integration page of the docs say there is a current [upstreaming effort](https://github.com/erlang/rebar3/pull/2859), but this effort was merged over half a year ago. Everything that follows is in the same subsection, so I have no way to know what the actual situation is.

### Solution

The docs should list the rebar3 plugins required by the _current_ version of ELP, and how to declare them.

### Notes

Does the current rebar3 integration also automatically fetch ELP itself? Or is directly downloading a binary still the best way to source it?

**Comment by robertoaloi** [comment]
Hi @i-am-linja Good call about the documentation. The rebar3 version with built-in support for ELP was released [4 days ago](https://github.com/erlang/rebar3/releases/tag/3.24.0). I plan to start the cleanup (including the documentation parts) soon.

You have three options for now:

* Wait until we modify ELP to use the built-in plugin instead of relying on a third-party plugin (~1 week)
* Use the old-style third-party plugin (not recommended, since we're getting rid of that)
* Create a `.elp.toml` file in the root of your project  and add a `[build_info]` section as explained [here](https://whatsapp.github.io/erlang-language-platform/docs/get-started/configure-project/elp-toml/#build_info). For simple rebar3 projects (no macros, no `rebar.config.script`, no parse transforms or hooks) that should be a good enough approximation and you won't need a rebar3 integration.

You need to install ELP yourself, either from source or binary. We need to figure out a good setup flow as you suggested [here](https://github.com/WhatsApp/erlang-language-platform/issues/49).

**Comment by robertoaloi** [comment]
ELP now requires `3.24.0` and uses the built-in manifest plugin. I updated the docs accordingly. We will need a ELP release for this to have an effect.
